In [8]:
import pandas as pd
import requests

In [9]:
api_key = ""
url = "https://api.gptzero.me/v2/predict/text"

In [11]:
data = pd.read_csv('UMS_2.csv')
data.head()

,Row,Sample Name,Transaction Id,Anon Student Id,Session Id,Time,Time Zone,Student Response Type,Student Response Subtype,Tutor Response Type,...,CF (AI_Evaluation),CF (AI_Rephrased_Response),CF (AI_Request_Counter),CF (AiEnabled),CF (Condition),CF (Counterbalanced),CF (Sequence),CF (tool_event_time),CF (tutor_event_time),Event Type
0,35,All Data,d2641eb584d67e3a09f5adfbc9c464b9,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:05,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:05:43.502 UTC,2024-08-07 21:05:43.503 UTC,NaN
1,39,All Data,e938580cb64f86e929d6bfac9f127187,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:08,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:08:16.076 UTC,2024-08-07 21:08:16.077 UTC,NaN
2,52,All Data,ed7aed67cb9cc3b017f311ee650d0c78,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:16,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:16:04.021 UTC,2024-08-07 21:16:04.022 UTC,NaN
3,55,All Data,d9c1996b89480729914c12a6b496503a,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:18,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:18:07.005 UTC,2024-08-07 21:18:07.006 UTC,NaN
4,327,All Data,1465bba28a4c0c4a66d723a4e8f5b515,Stu_00b5f036f5c4a9d12d0431b66b449927,ctat_session_f4cc9999-fb2c-4753-7b4c-29ae2e3c83b5,4/29/24 11:51,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Open-response only,"Scenario Carla, Scenario Kevin",NaN,2024-04-29 11:51:20.514 UTC,2024-04-29 11:51:20.516 UTC,NaN

In [12]:
filtered_data = data[
    ((data['Source of Truth: Obviously AI-generated'] == 1) & (data['Source of Truth: Authentic, Real Person'] == 0)) |
    ((data['Source of Truth: Obviously AI-generated'] == 0) & (data['Source of Truth: Authentic, Real Person'] == 1)) |
    (data['Source of Truth: Obviously AI-generated'] == 0.5)
]

filtered_data.head()

,Row,Sample Name,Transaction Id,Anon Student Id,Session Id,Time,Time Zone,Student Response Type,Student Response Subtype,Tutor Response Type,...,CF (AI_Evaluation),CF (AI_Rephrased_Response),CF (AI_Request_Counter),CF (AiEnabled),CF (Condition),CF (Counterbalanced),CF (Sequence),CF (tool_event_time),CF (tutor_event_time),Event Type
0,35,All Data,d2641eb584d67e3a09f5adfbc9c464b9,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:05,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:05:43.502 UTC,2024-08-07 21:05:43.503 UTC,NaN
1,39,All Data,e938580cb64f86e929d6bfac9f127187,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:08,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:08:16.076 UTC,2024-08-07 21:08:16.077 UTC,NaN
2,52,All Data,ed7aed67cb9cc3b017f311ee650d0c78,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:16,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:16:04.021 UTC,2024-08-07 21:16:04.022 UTC,NaN
3,55,All Data,d9c1996b89480729914c12a6b496503a,Stu_003e8f3cf4fd2af060aae025ded87e3b,ctat_session_d87b8a9a-4f7d-3a04-f65a-00e04d849336,8/7/24 21:18,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Mixed,"Scenario Kevin, Scenario Carla",NaN,2024-08-07 21:18:07.005 UTC,2024-08-07 21:18:07.006 UTC,NaN
4,327,All Data,1465bba28a4c0c4a66d723a4e8f5b515,Stu_00b5f036f5c4a9d12d0431b66b449927,ctat_session_f4cc9999-fb2c-4753-7b4c-29ae2e3c83b5,4/29/24 11:51,UTC,ATTEMPT,NaN,RESULT,...,NaN,NaN,NaN,NaN,Open-response only,"Scenario Carla, Scenario Kevin",NaN,2024-04-29 11:51:20.514 UTC,2024-04-29 11:51:20.516 UTC,NaN

In [22]:
filtered_data.shape

(1635, 50)

In [25]:
test_data = pd.read_csv('test_data_5.csv')
test_data.shape

(333, 4)

In [32]:
# random sample of test_data
test_sample = test_data.sample(200, random_state=42)
test_sample['Input'].str.split().str.len().sum()

10040

In [33]:
test_sample['Source of Truth: Obviously AI-generated'].value_counts()

Source of Truth: Obviously AI-generated
1.0    107
0.0     63
0.5     30
Name: count, dtype: int64

In [ ]:
classifications = []
confidence_scores = []
messages = []

for index, row in filtered_data.iterrows():
    text = row['Input']
    payload = {
        "document": text,
        "multilingual": False
    }
    headers = {
        "x-api-key": api_key,
        "Content-Type": "application/json",
        "Accept": "application/json"
    }
    response = requests.post(url, json=payload, headers=headers)
    output = response.json()

    document = output["documents"][0]  
    predicted_class = document["predicted_class"]  
    confidence_score = document["confidence_score"] 
    result_message = document["result_message"]

    classifications.append(predicted_class)
    confidence_scores.append(confidence_score)
    messages.append(result_message)

In [36]:
output

{'error': 'Monthly limit of 10,000 words has been reached for free users. Upgrade instantly by signing up for a plan at https://app.gptzero.me/app/subscription-plans'}

In [54]:
df_pred = test_sample.head(164)

In [ ]:
df_pred['Predicted Class'] = classifications
df_pred['Confidence Score'] = confidence_scores
df_pred['Result Message'] = messages

In [ ]:
df_pred.to_csv('GPTZero Predictions.csv', index=False)

In [16]:
df_pred = pd.read_csv('GPTZero Predictions.csv')

In [17]:
df_pred.head()

,Transaction Id,Anon Student Id,Input,Source of Truth: Obviously AI-generated,Predicted Class,Confidence Score,Result Message
0,2d42f2c81f8b8d4482f28ae603997d3e,Stu_0755ba73ee26e7e1ac55f6fb3ac68183,That's fantastic work on your math lessons! Ju...,0.5,ai,1.000000,Our detector is highly confident that the text...
1,1a15c5b4b61a8d887acb74a7d0b75d2f,Stu_e5c4e51beb25e4c6071cb5390865350f,"Carla, I know this is tough, and you're feelin...",1.0,ai,1.000000,Our detector is highly confident that the text...
2,9b43ad577b1b4e88b95673a7b38a5ef3,Stu_24d3594caca506a633cdb1344060326f,"Hey Kevin, awesome job hitting your math lesso...",1.0,ai,1.000000,Our detector is highly confident that the text...
3,5e1703ca0c72a4bcd51128cb81d1f02d,Stu_696b15b6731f9f08e5ededc09e976452,Hey Kevin! I'm really impressed with how hard ...,1.0,ai,0.999784,Our detector is highly confident that the text...
4,7c59162061969ab71549da4bf7826a9a,Stu_21623d82ce2fc82433719c8a365ffb0a,Awesome job on your math lessons this week! Ju...,1.0,ai,1.000000,Our detector is highly confident that the text...

In [18]:
print(df_pred['Predicted Class'].value_counts())
print(df_pred['Source of Truth: Obviously AI-generated'].value_counts())

Predicted Class
ai       114
human     50
Name: count, dtype: int64
Source of Truth: Obviously AI-generated
1.0    84
0.0    56
0.5    24
Name: count, dtype: int64

In [19]:
df_pred['Predicted Label'] = df_pred['Predicted Class'].apply(lambda x: 0 if x == 'human' else 1)
df_pred['Label 1 (0.5 = 1)'] = df_pred['Source of Truth: Obviously AI-generated'].apply(lambda x: 1 if x == 0.5 else x) # 0.5 is considered as 1

In [20]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(df_pred['Label 1 (0.5 = 1)'], df_pred['Predicted Label']))
print(classification_report(df_pred['Label 1 (0.5 = 1)'], df_pred['Predicted Label']))

[[20 36]
 [30 78]]
              precision    recall  f1-score   support

         0.0       0.40      0.36      0.38        56
         1.0       0.68      0.72      0.70       108

    accuracy                           0.60       164
   macro avg       0.54      0.54      0.54       164
weighted avg       0.59      0.60      0.59       164

In [21]:
df_pred['Label 2 (0.5 = 0)'] = df_pred['Source of Truth: Obviously AI-generated'].apply(lambda x: 0 if x == 0.5 else x) # 0.5 = 0

print(confusion_matrix(df_pred['Label 2 (0.5 = 0)'], df_pred['Predicted Label']))
print(classification_report(df_pred['Label 2 (0.5 = 0)'], df_pred['Predicted Label']))

[[25 55]
 [25 59]]
              precision    recall  f1-score   support

         0.0       0.50      0.31      0.38        80
         1.0       0.52      0.70      0.60        84

    accuracy                           0.51       164
   macro avg       0.51      0.51      0.49       164
weighted avg       0.51      0.51      0.49       164

In [ ]:
df_pred['True Label'] = df_pred['Source of Truth: Obviously AI-generated'].apply(lambda x: 2 if x == 0.5 else x) # 0.5 = 2

print(confusion_matrix(df_pred['True Label'], df_pred['Predicted Label']))
print(classification_report(df_pred['True Label'], df_pred['Predicted Label']))